/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BallywaterClinic;

import javax.swing.JTextArea;

/**
 *
 * @author jameskawala
 */
public class BallywaterGUI extends javax.swing.JFrame {

    /**
     * Creates new form BallywaterGUI
     */
    private PQInterface myPQueue;
    public BallywaterGUI() {
        myPQueue = new MyPriorityQueue();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderJLabel = new javax.swing.JLabel();
        NameJLabel = new javax.swing.JLabel();
        NameJText = new javax.swing.JTextField();
        SymptomJLabel = new javax.swing.JLabel();
        AgeJText = new javax.swing.JTextField();
        PriorityJLabel = new javax.swing.JLabel();
        SymptomJText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDisplay = new javax.swing.JTextArea();
        AddJButton = new javax.swing.JButton();
        DeleteJButton = new javax.swing.JButton();
        PriorityNumberButton = new javax.swing.JButton();
        ListPatientsJButton = new javax.swing.JButton();
        AgeJLabel = new javax.swing.JLabel();
        PriorityJTextField = new javax.swing.JTextField();
        ExitJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderJLabel.setText("Ballywater Clinic Vaccination App");

        NameJLabel.setText("Name:");

        NameJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameJTextActionPerformed(evt);
            }
        });

        SymptomJLabel.setText("Symptom:");

        PriorityJLabel.setText("Priority Level:");

        SymptomJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomJTextActionPerformed(evt);
            }
        });

        jTextAreaDisplay.setColumns(20);
        jTextAreaDisplay.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDisplay);

        AddJButton.setText("Add Patients");
        AddJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddJButtonActionPerformed(evt);
            }
        });

        DeleteJButton.setText("Delete Patients ");
        DeleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteJButtonActionPerformed(evt);
            }
        });

        PriorityNumberButton.setText("Priority Number ");
        PriorityNumberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriorityNumberButtonActionPerformed(evt);
            }
        });

        ListPatientsJButton.setText("List Patients ");
        ListPatientsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListPatientsJButtonActionPerformed(evt);
            }
        });

        AgeJLabel.setText("Age:");

        PriorityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriorityJTextFieldActionPerformed(evt);
            }
        });

        ExitJButton.setText("Exit Application ");
        ExitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgeJLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(HeaderJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PriorityJLabel)
                                            .addComponent(SymptomJLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SymptomJText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PriorityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AgeJText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NameJLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddJButton)
                            .addComponent(ListPatientsJButton))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ExitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DeleteJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(PriorityNumberButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameJLabel)
                    .addComponent(NameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeJLabel)
                    .addComponent(AgeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SymptomJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SymptomJLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriorityJLabel)
                    .addComponent(PriorityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddJButton)
                    .addComponent(DeleteJButton)
                    .addComponent(PriorityNumberButton))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListPatientsJButton)
                    .addComponent(ExitJButton))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameJTextActionPerformed

    private void SymptomJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SymptomJTextActionPerformed

    private void PriorityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriorityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriorityJTextFieldActionPerformed

    private void PriorityNumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriorityNumberButtonActionPerformed
        // TODO add your handling code here:
        jTextAreaDisplay.append("There are " + myPQueue.size() + " patients already in the queue "+ " \n ");
    }//GEN-LAST:event_PriorityNumberButtonActionPerformed

    private void ListPatientsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListPatientsJButtonActionPerformed
        // TODO add your handling code here:
        jTextAreaDisplay.append("The patient waiting in the queue...."+ "\n");
        jTextAreaDisplay.append(myPQueue.printPQueue()+"\n");
    }//GEN-LAST:event_ListPatientsJButtonActionPerformed

    private void ExitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitJButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitJButtonActionPerformed

    private void AddJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddJButtonActionPerformed
        // TODO add your handling code here:
        String name;
        String symptoms;
        int age;
        int priority;
        Integer priorityINT;
        
        Patients p = new Patients();
        name = NameJText.getText();
        symptoms = SymptomJText.getText();
         age = Integer.parseInt(AgeJText.getText());
         
         
        p.setName(name);
        p.setAge(age);
       
        
        
        priorityINT = new Integer (PriorityJTextField.getText());
        priority = priorityINT.intValue();
        myPQueue.enqueue(priority, p);
        
        jTextAreaDisplay.append(NameJText.getText() + "Your details have been successfully added to the queue" + "\n");
  NameJText.setText("");
  AgeJText.setText("");
  SymptomJText.setText("");
  PriorityJTextField.setText("");
  
 if(p.getAge() >=0 && p.getAge()<=17){
      
      priority=1;
      
      jTextAreaDisplay.append(NameJText.getText()+ "was added" + "\n");
       myPQueue.enqueue(priority,p);
 }
 
  if(p.getAge() >=18 && p.getAge()<=64){
      
      priority=6;
      
      jTextAreaDisplay.append(NameJText.getText()+ "was added" + "\n");
       myPQueue.enqueue(priority,p);
 }
  
if(p.getAge() >=18 && p.getAge()<=29){
      
      priority=2;
      
      jTextAreaDisplay.append(NameJText.getText()+ "was added" + "\n");
     
 }

if(p.getAge() >=30 && p.getAge()<=44){
      
      priority=3;
      
      jTextAreaDisplay.append(NameJText.getText()+ "was added" + "\n");
     
 }

if(p.getAge() >=45 && p.getAge()<=54){
      
      priority=4;
      
      jTextAreaDisplay.append(NameJText.getText()+ "was added" + "\n");
   
 }

if(p.getAge() >=55 && p.getAge()<=64){
      
      priority=5;
      
      jTextAreaDisplay.append(NameJText.getText()+ "was added" + "\n");
     
 }

if(p.getAge() >=65 && p.getAge()<=69){
      
      priority=7;
      
      jTextAreaDisplay.append(NameJText.getText()+ "was added" + "\n");
      
 }

if(p.getAge() >=70 && p.getAge()<=79){
      
      priority=8;
      
      jTextAreaDisplay.append(NameJText.getText()+ "was added" + "\n");
     
 }

if(p.getAge() >=80 && p.getAge()<=89){
      
      priority=9;
      
      jTextAreaDisplay.append(NameJText.getText()+ "was added" + "\n");
      
 }

if(p.getAge() >=90 && p.getAge()<=99){
      
      priority=7;
      
      jTextAreaDisplay.append(NameJText.getText()+ " was added " + " \n ");
      
 }

else if(p.getAge() >=18 && p.getAge()<=69){
    
    priority=6;
    
    jTextAreaDisplay.append(NameJText.getText()+ "was added" + "\n");
  
 }

else {
             jTextAreaDisplay.append("Error occured, cant show any patients");
}
    }//GEN-LAST:event_AddJButtonActionPerformed

    private void DeleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteJButtonActionPerformed
        // TODO add your handling code here:
        if(!myPQueue.isEmpty()){
            PQElement pqelem = (PQElement)myPQueue.dequeue();
            Patients p1 = (Patients)pqelem.getElement();

            jTextAreaDisplay.append(" The patient should be seen " + p1.getName());
            jTextAreaDisplay.append(" Age: " + p1.getAge());
            jTextAreaDisplay.append(" Symptoms: " + p1.getSymptoms());
            jTextAreaDisplay.append(" Priority level " + pqelem.getKey()+ " \n ");
        }
        else
        jTextAreaDisplay.append(" There are no more patients "+ " \n ");

    }//GEN-LAST:event_DeleteJButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddJButton;
    private javax.swing.JLabel AgeJLabel;
    private javax.swing.JTextField AgeJText;
    private javax.swing.JButton DeleteJButton;
    private javax.swing.JButton ExitJButton;
    private javax.swing.JLabel HeaderJLabel;
    private javax.swing.JButton ListPatientsJButton;
    private javax.swing.JLabel NameJLabel;
    private javax.swing.JTextField NameJText;
    private javax.swing.JLabel PriorityJLabel;
    private javax.swing.JTextField PriorityJTextField;
    private javax.swing.JButton PriorityNumberButton;
    private javax.swing.JLabel SymptomJLabel;
    private javax.swing.JTextField SymptomJText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDisplay;
    // End of variables declaration//GEN-END:variables
}
